### ISSUE TITLE
Requesting push access

### ISSUE THREAD

**Issue by jtbandes** [ros2-gbp/rosbridge_suite-release#1]
Hi,
Myself and some other @foxglove team members will be helping to maintain the rosbridge_suite repo and improve ROS 2 support. In order to make releases for ROS 2 using bloom we will need access to this repo.

GitHub usernames: @jtbandes, @defunctzombie, @amacneil

Thank you!

**Comment by nuclearsandwich** [comment]
The three of you have been sent invitations to admin the repository as outside collaborators. At some point in the coming weeks we'll have you transition to team members within the organization but that work is not quite ready yet.

Once you've accepted the invitation and confirmed access please close this issue. If you run into any issues please let me know. Thanks!

**Comment by jtbandes** [comment]
Successfully got access, thanks!

**Comment by amacneil** [comment]
Thanks!
